### ISSUE TITLE
How to get variogram parameters from a GridSearch

### ISSUE THREAD

**Issue by olaurendin** [GeoStat-Framework/PyKrige#104]
Hi, 
I have tried to use the GridSearchCV from sklearn with a Krige instance as given in the examples files. This example shows how to get some parameters of the best variogram and the kriging system used such as whether it is universal or ordinary kriging or if it is a linear or spherical variogram once the fitting is done. However, I have not been able to find out how to get the specific parameters of the best variogram like its sill, range and nugget in the case of a spherical variogram.
I am aware that it might be a sklearn specific question, but if you have faced this issue in the past, can you tell me how you solved it?
Also, I know that I could use the predict statement from sklearn to counter this issue, but I would rather get the variogram parameters and use the execute statement of an OrdinaryKriging instance if possible.
Btw, I am quite new to sklearn and kriging so I am sorry if my question is not relevant.

Thanks in advance

**Comment by rth** [comment]
> However, I have not been able to find out how to get the specific parameters of the best variogram like its sill, range and nugget in the case of a spherical variogram.
I am aware that it might be a sklearn specific question, but if you have faced this issue in the past, can you tell me how you solved it?

In `GridSearchCV` one can provide a list of custom dictionaries with parameters. For instance, something along the lines of the following,
```py
import numpy as np
from pykrige.rk import Krige
from pykrige.compat import GridSearchCV


# 3D Kring param opt

param_dict3d = {"method": ["ordinary3d"], "variogram_model": ["linear"],
                 "variogram_parameters": [{'slope': 1.0, 'nugget': 1.0},
                                          {'slope': 2.0, 'nugget': 1.0}]
               }
                


estimator = GridSearchCV(Krige(), param_dict3d, verbose=True)

# dummy data
X3 = np.random.randint(0, 400, size=(100, 3)).astype(float)
y = 5 * np.random.rand(100)

# run the gridsearch
estimator.fit(X=X3, y=y)

print(estimator.cv_results_)
```

where `variogram_parameters` are defined as needed would have worked I think.
Except that `Krige` wrapper class currently doesn't accept the `variogram_parameters` as input. Adding it to `__init__` then passing it through in fit [here](https://github.com/bsmurphy/PyKrige/blob/22c8a6955719168235b7f4d8b989b78575c12c82/pykrige/rk.py#L72) should be fairly straightforward. A PR to add it would be very welcome. 

(Note that `param_dict3d` can also be a list of dicts, as different variogram models take different parameters).

> Also, I know that I could use the predict statement from sklearn to counter this issue, but I would rather get the variogram parameters and use the execute statement of an OrdinaryKriging instance if possible.

One `GridSearchCV` has been fitted, you can get the best parameters by looking at its `cv_results_` and `best_params_` attributes (cf [scikit-learn docs](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html)). Then once you know the best parameters, you could indeed just pass them to the `OrdinaryKriging` class. Hope this answers your question.

**Comment by MuellerSeb** [comment]
Closing for now. Feel free to re-open if you have further questions.
