### ISSUE TITLE
Universal Kriging: Geographic Coordinates support

### ISSUE THREAD

**Issue by allenea** [GeoStat-Framework/PyKrige#121]
When might geographic coordinates for Universal Kriging be implemented and released?

**Comment by rth** [comment]
I think https://github.com/bsmurphy/PyKrige/issues/56 would be a general way of addressing this. We are looking for someone to make progress there :)

Alternatively, directly adding support for geographic coordinates in Universal Kriging (mostly by adapting how this is done in Ordinary Kriging) would also be an acceptable short term solution.

Contributions are very welcome!

**Comment by MuellerSeb** [comment]
When refactoring the code to use a single base-class providing the common methods, this will be done.

**Comment by MuellerSeb** [comment]
We will address this with #143. Closing for now. Re-open if you want.
