### ISSUE TITLE
How to export the estimate in 3d without the method kt.write_asc_grid()

### ISSUE THREAD

**Issue by heberallin** [GeoStat-Framework/PyKrige#122]
Hi, I'm testing pykrige for a week now and I have the following question: How to export the estimate in 3d without the method **kt.write_asc_grid()**

In 2D I have no problem, but in 3D this method (kt.write_asc_grid ()) is not implemented.

**This is part of my code:**

_**Variogram:**_

ok3d = OrdinaryKriging3D(x,y,z,val,variogram_model='spherical', nlags=10, enable_plotting=True, verbose=True)

_**Grid Set:**_

gridx= np.linspace(0,410, num=41, endpoint=False)
gridy= np.linspace(0,610, num=61, endpoint=False)
gridz= np.linspace(0,150, num=15, endpoint=False)
zg, yg, xg = np.meshgrid(gridz, gridy, gridx, indexing='ij')

_**Kriging and variance:**_

k3d, ss3d = ok3d.execute('grid', gridx, gridy, gridz)

Thank a lot!.

**Comment by heberallin** [comment]
Solved!.

**Comment by MuellerSeb** [comment]
You could use [pyevtk](https://github.com/pyscience-projects/pyevtk). How did you solve it?

**Comment by MuellerSeb** [comment]
Closing it due to inactivity. Feel free to re-open.
