### ISSUE TITLE
Interface with GSTools

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/PyKrige#124]
Hey there,

We are working on a project for geostatistical simulaton (https://github.com/GeoStat-Framework), where we, among other things, provide tools to generate spatial random fields based on variogram methods.

Now we wanted to provide conditioned random fields by incorporating data via Kriging and stumbled over your neat project! Your input information is totally similar to our approach, so I wrote a small interface for pykrige, which looks and works like this:

```python
import numpy as np
from gstools import Gaussian
from pykrige.ok import OrdinaryKriging

data = np.array([[0.3, 1.2, 0.47],
                 [1.9, 0.6, 0.56],
                 [1.1, 3.2, 0.74],
                 [3.3, 4.4, 1.47],
                 [4.7, 3.8, 1.74]])

gridx = np.arange(0.0, 5.5, 0.1)
gridy = np.arange(0.0, 5.5, 0.1)

# a GSTools based covariance model
model = Gaussian(dim=2, len_scale=1, anis=0.2, angles=0.5, var=0.5, nugget=0.1)

OK1 = OrdinaryKriging(
    data[:, 0], data[:, 1], data[:, 2],
    **model.pykrige_kwargs,  # magic
)
z1, ss1 = OK1.execute('grid', gridx, gridy)
```

![gstools_pykrige](https://user-images.githubusercontent.com/19690642/57859231-d4f30c80-77f2-11e9-96e3-8f0fb10b24a6.png)

We provide a flexible [Covariance-Class](https://gstools.readthedocs.io/en/latest/covmodel.base.html#gstools.covmodel.base.CovModel) that contains all informations about the variogram and has a huge range of methods (like spectrum, spectral density, integral scale, variogram fitting, anisotropy, rotation... and so on) You can also create user defined models by just defining a correlation function (See here: https://github.com/GeoStat-Framework/GSTools#user-defined-covariance-models)

This class now also contains a property called [`pykrige_kwargs`](https://github.com/GeoStat-Framework/GSTools/blob/d7dd7480a8133a64251254673753e71838a31d3d/gstools/covmodel/base.py#L364) which can be used with your project as shown above. Only difference:
The anisotropy ratios are calculated inversely in both packages. So `anis=0.2` in GSTools will result in `anisotropy_scaling=1.0/0.2` in pykrige.
The angles are also calculated differently. Your orientation is the opposite of ours and you use deg instead of rad. So `angles=0.5` in GSTools will result in `anisotropy_angle=-np.rad2deg(0.5)` in pykrige.

Same in 3D.  `pykrige_kwargs` takes care of that depending on the dimension.

But still, the provided functionality overlaps perfectly! And I think, If you are still working on refactoring your code, It could be a cool thing working together!

What do you think about that? Maybe we can join forces! I'd love to have a chat about that.

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
We just updated our rotation behavior in GSTools (https://github.com/GeoStat-Framework/GSTools/commit/0dfaf5f2ec8563d701d4c2e6e95c60e4312c06f4), so that the orientation is the same as in PyKrige.
Also we now provide simple and ordinary kriging in GSTools and recommend your package for the more fancier stuff.
The above mentioned Interface to PyKrige will be included in our next release ``GSTools 1.1.0``. I hope you are OK with that.

**Comment by mjziebarth** [comment]
Hey Sebastian,

please excuse the late response. Personally, I am quite busy right now and seeing that there has been no response the last 2 weeks, I suppose it's similar for the others. Looking at the code you provided, it seems like an excellent integration and I can't see any reason against including it in your release. While I can't speak for the others, I suspect they feel similarly.

Regarding working together, do you have anything specific in mind? I have a feeling that the project has become kind of a side project for everyone involved so that fresh air is probably helpful :-)
What do you say, @bsmurphy, @rth, @basaks ?

Cheers,
Malte

**Comment by MuellerSeb** [comment]
Hey Malte,

thanks for the nice words. One thing I have in mind is, that your routines could be able to directly take a covariance model from gstools directly, since the presented interface with a provided kwargs dictionary is a bit of a hack. I think it would be nice, if one could provide an instance of our covariance model as a variogram model to your routines, like:

    model = Gaussian(dim=2, len_scale=1, anis=0.2, angles=0.5, var=0.5, nugget=0.1)
    
    OK1 = OrdinaryKriging(
        data[:, 0], data[:, 1], data[:, 2],
        variogram_model=model,
    )

Then there could be a check, for example, at https://github.com/bsmurphy/PyKrige/blob/a4db3003b0b5688658c12faeb95a5a8b2b14b433/pykrige/ok.py#L216 if the given model is an instance of our model and everything from the input can be overwritten with information from the model and the variogram_model can be set internally as ``"custom"``. I think this could be quite convenient.

**Comment by MuellerSeb** [comment]
I created a pull request providing the above mentioned Interface: https://github.com/bsmurphy/PyKrige/pull/125

**Comment by rth** [comment]
Thanks for your PR, it is quite nice!

> And I think, If you are still working on refactoring your code, It could be a cool thing working together!

We have somewhat a lack of maintainer resources at the moment.

If you have an interest and the availability to improve PyKrige that would be very much appreciated! Personnally, I won't be able to contribute much beyound reviewing some PRs. I got into pykrige in 2015 for a side project, and haven't realy used in my work/outside of work projects since.

**Comment by MuellerSeb** [comment]
@rth and @bsmurphy : If there is interest in joining forces, one idea could be to integrate PyKrige into the [GeoStat-Framework](https://github.com/GeoStat-Framework). Then we could care about PyKrige together and since the Framework is a GitHub organization, it would be easier for newbies to join the project and create a community maintained package base.

One step in that direction is of course https://github.com/bsmurphy/PyKrige/pull/125. (Sorry for the long delay!)

Maybe we could have a conversation about that. What do you think?

Cheers, Sebastian

**Comment by MuellerSeb** [comment]
First step done with #125
