### ISSUE TITLE
saving the fitted model and save predicted file

### ISSUE THREAD

**Issue by SRKabir** [GeoStat-Framework/PyKrige#129]
1. Fitting and predicting works perfectly fine for me. However, is it possible to save the fitted model in the disk? and load afterwords?

2. While I could write the predicted files in asc format using .write_asc_grid() for ordinary/universal kriging, I couldn't manage to do it for RK. I have managed to save the files using Rasterio, but wondering if files could be saved using .write_asc_grid() just like other methods?

Regards
Kabir

**Comment by drewyang-datavedik** [comment]
> 1. Fitting and predicting works perfectly fine for me. However, is it possible to save the fitted model in the disk? and load afterwords?
> 2. While I could write the predicted files in asc format using .write_asc_grid() for ordinary/universal kriging, I couldn't manage to do it for RK. I have managed to save the files using Rasterio, but wondering if files could be saved using .write_asc_grid() just like other methods?
> 
> Regards
> Kabir

```
uk = OrdinaryKriging(X, np.zeros(X.shape), y, variogram_model='gaussian',)

pickle.dump( uk, open( "uktest.p", "wb" ) )

uk_load = pickle.load( open( "uktest.p", "rb" ) )

y_pred, y_std = uk_load.execute('grid', X_pred, np.array([0.]))
```
Hi Kabir,
I encountered this demand as well today, which I need to save my kriging model for later use.
I tried to pickle it, it works perfectly.
Good luck! : )

**Comment by MuellerSeb** [comment]
I think there are enough options to save such data with numpy or pickle as demonstrated above.
