### ISSUE TITLE
Getting kriging interpolated grid  with None values where the samples are far from the semivariogram range

### ISSUE THREAD

**Issue by carlosfelg** [GeoStat-Framework/PyKrige#134]
How can I get an interpolated grid with None (or no data) values where all the data neighbours (samples) are far from the variogram range value? I mean, I would like to use the variogram range value as constraining when there is no input data inside the range radio.

**Comment by MuellerSeb** [comment]
What do you mean by "variogram range value"? I really don't understand what you mean. 
To try a shot in the dark, one thing of interest could be the estimated mean for ordinary krging. Do you mean that?

**Comment by carlosfelg** [comment]
Dear Sebastian, 

Thanks a lot for your reply. 

I am considering
that the variogram (used for ordinary kriging) has 4 parameters: Model
(spheric, exponential, gaussian,...), Nugget Effect, Contribution
(nugget effect + contribution= sill) and Range (the maximum distance for
spatial data correlation). 

I have been used the pykrige ordinary
kriging and I have found that the interpolation is made in all of the
grid locations, even when THERE IS NO INPUT SAMPLES CLOSE (I mean with
distance lower than the variogram range value) to some grid locations. I
was expecting that the pykrige ordinary kriging will return a None value
(no data, meaning no interpolation) for the grid locations far from the
samples. 

I hope I have been clear. 

i look forward to hearing from
you. 

Best regards 

Em 26-01-2020 18:13, Sebastian Müller escreveu:


> What do you mean by "variogram range value"? I really don't
understand what you mean.
> To try a shot in the dark, one thing of
interest could be the estimated mean for ordinary krging. Do you mean
that? 
> 
> --
> You are receiving this because you authored the
thread.
> Reply to this email directly, view it on GitHub [1], or
unsubscribe [2].

-- 
Carlos A Felgueiras 
Computer Science PhD
SPRING
GIS Software Manager
Image Processing Division - DPI
Brazilian National
Institute for Space Research - INPE
Fone: (12)3208-6469 or
(12)981449544
 

Links:
------
[1]
https://github.com/GeoStat-Framework/PyKrige/issues/134?email_source=notifications&amp;email_token=ALDKQOCDLBORBB5MSN4FLFTQ7X4HNA5CNFSM4KGG4ALKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ56BGQ#issuecomment-578543770
[2]

**Comment by MuellerSeb** [comment]
In [OrdinaryKriging.execute](https://github.com/GeoStat-Framework/PyKrige/blob/a31dbbb9ee22d89da2378f28dc11c0d882ae564d/pykrige/ok.py#L578)

https://github.com/GeoStat-Framework/PyKrige/blob/a31dbbb9ee22d89da2378f28dc11c0d882ae564d/pykrige/ok.py#L578

you can set ``n_closest_points`` to only take a certain amount of nearby values into account. Maybe this is helps?

**Comment by MuellerSeb** [comment]
Solved.

**Comment by carlosfelg** [comment]
What distance value is considered, inside the ordinary kriging function, to define the closest points? The n_closest_points parameter is the minimum or the maximum number of closest points?

**Comment by carlosfelg** [comment]
Dear Sebastian, 

I have tried to use the n_closest_points parameter
but it seems that it does not work properly. 

What distance value is
considered, inside the ordinary kriging function, to define the closest
points? The n_closest_points parameter is the minimum or the maximum
number of closest points? 

Regards 

- 
Carlos A Felgueiras 
Computer
Science PhD
SPRING GIS Software Manager
Image Processing Division -
DPI
Brazilian National Institute for Space Research - INPE
Fone:
(12)3208-6469 or (12)981449544

Em 28-01-2020 07:54, Sebastian Müller
escreveu: 

> In OrdinaryKriging.execute [1] 
> 
>
https://github.com/GeoStat-Framework/PyKrige/blob/a31dbbb9ee22d89da2378f28dc11c0d882ae564d/pykrige/ok.py#L578
[1] 
> 
> you can set n_closest_points to only take a certain amount of
nearby values into account. Maybe this is helps? 
> 
> --
> You are
receiving this because you authored the thread.
> Reply to this email
directly, view it on GitHub [2], or unsubscribe [3].

-



Links:
------
[1]
https://github.com/GeoStat-Framework/PyKrige/blob/a31dbbb9ee22d89da2378f28dc11c0d882ae564d/pykrige/ok.py#L578
[2]
https://github.com/GeoStat-Framework/PyKrige/issues/134?email_source=notifications&amp;email_token=ALDKQOH7CEEFTYKFOXOLSU3RAAFH5A5CNFSM4KGG4ALKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKC3UTA#issuecomment-579189324
[3]

**Comment by MuellerSeb** [comment]
``n_closest_points`` is exact unless there are less data points in total. The n clostest points are determined by scipys [KDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html#scipy.spatial.KDTree)

> ...but it seems that it does not work properly.

What exactly do you mean?

**Comment by carlosfelg** [comment]
My doubt is: What is the distance value for a point to be considered
a closer point? 

Em 28-01-2020 11:02, Sebastian Müller escreveu: 

>
n_closest_points is exact unless there are less data points in total.
The n clostest points are determined by scipys KDTree [1] 
> 
>> ...but
it seems that it does not work properly.
> 
> What exactly do you mean?

> 
> --
> You are receiving this because you modified the open/close
state.
> Reply to this email directly, view it on GitHub [2], or
unsubscribe [3].

-- 
Carlos A Felgueiras 
Computer Science PhD
SPRING
GIS Software Manager
Image Processing Division - DPI
Brazilian National
Institute for Space Research - INPE
Fone: (12)3208-6469 or
(12)981449544
 

Links:
------
[1]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html#scipy.spatial.KDTree
[2]
https://github.com/GeoStat-Framework/PyKrige/issues/134?email_source=notifications&amp;email_token=ALDKQOEYLNNBAPAJXYVS43TRAA3HZA5CNFSM4KGG4ALKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKDM3GI#issuecomment-579259801
[3]

**Comment by MuellerSeb** [comment]
The number of the closest points is fixed and not  determined by a search radius. If you have a dense data set, the n closest points would be rather near.

This needs to be improved in the future.

**Comment by MuellerSeb** [comment]
#143 addresses the missing search radius.

Closing for now due to inactivity. Feel free to re-open.
