### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by victortm** [GeoStat-Framework/PyKrige#135]
Hi,

I'm trying to get a variogram using pykrige.ok.OrdinaryKriging function but I'm getting the next error:

![image](https://user-images.githubusercontent.com/10722495/72977649-35e8d080-3dd5-11ea-929c-e01d027546fc.png)

I'm passing float values and longitude/latitude coordinates in decimal degrees.

I don't know if it could be related to this issue but I've found something that doesn't make so much sense to me in the documentation:

![image](https://user-images.githubusercontent.com/10722495/72977923-c32c2500-3dd5-11ea-8f83-22dff08aa3de.png)

When longitude has West component, the result is negative, so is out of that [0,360] longitude range specified in the doc. Feel free to correct me if I'm wrong.

Thanks in advance and best regards

**Comment by MuellerSeb** [comment]
Could you provide a minimal example to reproduce the error?

**Comment by victortm** [comment]
Of course.

There you have some samples I'm working with:

![image](https://user-images.githubusercontent.com/10722495/73167893-026db500-40f9-11ea-96f5-2a59c9084a00.png)

Ignore ID parameter.

And this is how I'm calling the function:

![image](https://user-images.githubusercontent.com/10722495/73167945-23cea100-40f9-11ea-95f6-fba3b32f49b1.png)

**Comment by MuellerSeb** [comment]
In your example all data is in the same location. So the bining of the data for the variogram estimation results in degenerate Intervals. I get the same error with:

```python
from pykrige import OrdinaryKriging as OK
lon = [-3.1, -3.1, -3.1]
lat = [40.0, 40.0, 40.0]
val = [1.1, 1.2, 1.3]
kr = OK(lon, lat, val, coordinates_type="geographic")
```
```bash
Traceback (most recent call last):

  File "test.py", line 6, in <module>
    kr = OK(lon, lat, val, coordinates_type="geographic")

  File "/usr/local/lib/python3.6/dist-packages/pykrige/ok.py", line 253, in __init__
    weight, self.coordinates_type)

  File "/usr/local/lib/python3.6/dist-packages/pykrige/core.py", line 482, in _initialize_variogram_model
    variogram_function, weight)

  File "/usr/local/lib/python3.6/dist-packages/pykrige/core.py", line 580, in _calculate_variogram_model
    args=(lags, semivariance, variogram_function, weight))

  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/_lsq/least_squares.py", line 786, in least_squares
    raise ValueError("`x0` is infeasible.")

ValueError: `x0` is infeasible.
```

**Your data-locations need to be pairwise different!**

**Comment by victortm** [comment]
Thanks, now works!

**Comment by MuellerSeb** [comment]
Solved.
