### ISSUE TITLE
Hierarchical kriging model for variable-fidelity surrogate modeling

### ISSUE THREAD

**Issue by AmosJoseph** [GeoStat-Framework/PyKrige#139]
Excuse me,can PyKrige conduct Hierarchical kriging model for variable-fidelity surrogate modeling?

Best regards!

**Comment by MuellerSeb** [comment]
Hey there,
At the moment we don't plan to implement this.
AFAIK, HK can be seen as an extension to external drift kriging (EDK), so you could create a workflow that mimics HK with pykrige in two steps:
- first use ordinary kriging for the low-fidelity part
- then use external driftt kriging for the high-fidelity part (with the low fidelity part as external drift)

Hope that helps. (See here: https://arc.aiaa.org/doi/10.2514/1.J051354)

**Comment by AmosJoseph** [comment]
OK，many thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sebastian Müller"<notifications@github.com&gt;; 
发送时间: 2020年3月27日(星期五) 凌晨2:05
收件人: "GeoStat-Framework/PyKrige"<PyKrige@noreply.github.com&gt;; 
抄送: "Joseph"<544591929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GeoStat-Framework/PyKrige] Hierarchical kriging model for variable-fidelity surrogate modeling (#139)





 
Hey there,
 At the moment we don't plan to implement this.
 AFAIK, HK can be seen as an extension to external drift kriging (EDK), so you could create a workflow that mimics HK with pykrige in two steps:
  
first use ordinary kriging for the low-fidelity part
 
then use external driftt kriging for the high-fidelity part (with the low fidelity part as external drift)
  
Hope that helps. (See here: https://arc.aiaa.org/doi/10.2514/1.J051354)
