### ISSUE TITLE
Custom variogram example

### ISSUE THREAD

**Issue by NikhilDupally** [GeoStat-Framework/PyKrige#148]
Could you provide an example of using a custom variogram function?

**Comment by MuellerSeb** [comment]
Hey there,

you can use a CovModel from GSTools:
https://geostat-framework.readthedocs.io/projects/pykrige/en/stable/examples/gstools_covmodel.html#sphx-glr-examples-gstools-covmodel-py

And you can easily define your own one, as described here:
https://geostat-framework.readthedocs.io/projects/gstools/en/stable/examples/02_cov_model/00_intro.html#introductory-example

Does that help?

**Comment by NikhilDupally** [comment]
Is there any way i could use variogram from scikit-Gstat module.

[From here](https://mmaelicke.github.io/scikit-gstat/reference/variogram.html#skgstat.Variogram.__init__)
with the above parameters.

**Comment by MuellerSeb** [comment]
As far as I know, scikit-gstat provides some basic kriging functionality itself.
But it is not possible to use their variogram-models with PyKrige.

**Comment by mmaelicke** [comment]
@NikhilMunna, while @MuellerSeb is right that you cannot pass the scikit-gstat Variogram to pykrige, there is an experimental interface.
In fact, the Github version of scikit-gstat has an interface to pykrige. It will be released with the 0.2.8 release on PyPI. It is still experimental and is thus neither documented nor tested in detail. I am planning to do that in the next weeks...
Here: https://github.com/mmaelicke/scikit-gstat/blob/f16afae9337ddf10814cb06a1461a44e0f0ec95f/skgstat/interfaces/pykrige.py#L29
is the respective code. You would use the last function in that file. I am also working on an Interface to gstools.CovModel. If you want to go that route, it would be nice to report errors to scikit-gstat.
