### ISSUE TITLE
Classification Kriging

### ISSUE THREAD

**Issue by mralbu** [GeoStat-Framework/PyKrige#164]
Thanks for this great package! I was introduced to regression kriging reading the documentation and found it super useful.
I've created a ClassificationKriging class adapting RegressionKriging to work with categorical variables, by mapping the scikit-learn classifiers predict_proba simplexes to an isometric space using the [ilr transform](https://en.wikipedia.org/wiki/Compositional_data), and kriging/interpolating the residuals of the (also ilr transformed) observed data. 
I am far from being an expert on geostatistics or compositional data analysis, but I believe this method corresponds to the [Simplicial Indicator Kriging](http://ns.leg.ufpr.br/lib/exe/fetch.php/pessoais:abtmartins:pawlowsky.pdf) [method](http://www.leg.ufpr.br/lib/exe/fetch.php/pessoais:sn1100-103o0651-0656_tolosanadelgado.pdf). 
Do you think this method could be a good addition to PyKrige? Initial implementation avaiable in the [classification-kriging branch](https://github.com/mralbu/PyKrige/tree/classification-kriging).

**Comment by MuellerSeb** [comment]
This sounds interesting! I'll have a look at this, when I've got some spare time.
@mralbu : Can you open a PR with this branch? Even if this is still work in progress, this would be the best place to discuss details ;-)

Thanks for your support!
Seb

**Comment by mralbu** [comment]
Opened pull request #165.

**Comment by MuellerSeb** [comment]
Merged into develop.
