### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by ghost** [GeoStat-Framework/PyKrige#177]
Hi, I am Civil Engineering graduate student, I would like to use kriging to obtain the correlation and the surface between 2 laboratory input data and one laboratory result output data. However, I do not have a strong statistics background. I was wondering, if you can give some kind of guidance on what to do. 

My problem is about experimental centrifuge soil models, there I can define two input data of the model and then I performed the test and I obtained an output result. The thing is that I do not have a lot of tests (about 20). 

Any suggestion on how to start will be really appreciated.

**Comment by MuellerSeb** [comment]
Could you provide some more information?

If you want to interpolate measured data, kriging is totally fine and you could for example start with this tutorial:
https://geostat-framework.readthedocs.io/projects/pykrige/en/stable/examples/00_ordinary.html#sphx-glr-examples-00-ordinary-py

If you just want to obtain correlation I think you could use variogram estimation provided by [GSTools](https://github.com/GeoStat-Framework/GSTools).
