### ISSUE TITLE
BUG: write_asc_grid function does not run as expected

### ISSUE THREAD

**Issue by Amos-Zhao** [GeoStat-Framework/PyKrige#197]
### kriging_tools.py  line 73 
I got  abs((x[-1] - x[0]) / (x.shape[0] - 1))   calculated as 0.999999999999998 , while dx   calculated as 1, so the function didn't work.
Is there any way to overcome this problem

**Comment by MuellerSeb** [comment]
Hey there,

I see the problem:
https://github.com/GeoStat-Framework/PyKrige/blob/09fe0183aa8e47ceb585a67408e08a4a4ffaced9/pykrige/kriging_tools.py#L74

This should be implemented with a safer comparison of floats.

Could you give a minimal example to reproduce this behavior? maybe you could also correct the values for `x` and `y`, to make the routine work.

Cheers, Sebastian

**Comment by Amos-Zhao** [comment]
```python
from pykrige import kriging_tools as kt
from pykrige.ok import OrdinaryKriging


import numpy as np
from hdhm.grid import RasterGrid

data = np.array(
    [
        [253387, 3496927, 2],
        [300000, 3529426, 10],
        [256087, 3536927, 6],
    ]
)

file_path = "huaihe/dem.txt"

grid, x, y, cell, no_data = kt.read_asc_grid(file_path)

OK = OrdinaryKriging(
    data[:, 0],
    data[:, 1],
    data[:, 2],
    variogram_model="linear",
    verbose=False,
    enable_plotting=False,
)
dem = RasterGrid(file_path)
z, ss = OK.execute("grid", x, y)
kt.write_asc_grid(x, y, z, filename="amos.asc", style=2)
```
[dem.txt](https://github.com/GeoStat-Framework/PyKrige/files/6609525/dem.txt)

**Comment by Amos-Zhao** [comment]
I'm trying to convert result[z] to asc file by using `numpy.savetxt("filename.txt",a)` and following code

> z = np.squeeze(np.array(z))
 z = np.flip(z, axis=0)
 np.savetxt("result.asc",z)

Thanks for your response.

**Comment by MuellerSeb** [comment]
But remember that just because of the `*.asc` ending, this is not a valid ESRI-Grid file.
