### ISSUE TITLE
zmap IO

### ISSUE THREAD

**Issue by MarkTNO** [GeoStat-Framework/PyKrige#198]
Good evening,

I have used PyKrige for our research at TNO, which is really helpful!
I have added .zmap (useful for Petrel and QGIS) reading and writing functionality to kriging_tools.py. Would you be interested in adding this? 
I tried to push my branch but did not get permission to do so.

Kind regards,
Mark Vrijlandt
TNO

**Comment by MuellerSeb** [comment]
Hey there,
nice to hear. We are always interested in contributions. Could you create a pull request? Then I can review your additions :wink:

Cheers, Sebastian
