### ISSUE TITLE
how to custom variogram_function with non-parametric meachine learning models like SVR, RF, MLP etc.

### ISSUE THREAD

**Issue by sunshineYin** [GeoStat-Framework/PyKrige#200]
Hello, 

I want to make modifications on variogram_functions of kriging interpolation. 

Because I think the categories of existing variogram_functions are not really enough, and the fitting effect is also not really good. So I want to use some non-parametric models, such as svr, random forest, mlp, etc. to fit the variogram function, because they have larger capacity.

The question is: in this case, how should I design the variogram function? Because the models are non-parametric here, the input of them are X and y, (that is d and gamma(d)), which are different from existing functions like linear, exponential, etc. Could you give me some help? (maybe some examples)

Thank you a lot!

**Comment by MuellerSeb** [comment]
Hey there,

keep in mind, that variogram functions need to fulfill some mathematically requirements like *conditional negative semidefiniteness* (CNSD), so the estimated kriging variance is always non-negative (see Webster 2007).

For references on valid variogram models see here:
- Hans Wackemagel (2003): Multivariate Geostatistics
- Webster & Oliver (2007): Geostatistics for Environmental Scientists

Also, you can use variogram models from GSTools with PyKrige. That means, you can use all models presented there and the fitting routines provided by GSTools. Have a look here:
- https://geostat-framework.readthedocs.io/projects/gstools/en/stable/examples/05_kriging/02_pykrige_interface.html#sphx-glr-examples-05-kriging-02-pykrige-interface-py
- https://geostat-framework.readthedocs.io/projects/gstools/en/stable/examples/03_variogram/index.html

Beside that, what do you exactly mean with
> Because I think the categories of existing variogram_functions are not really enough, and the fitting effect is also not really good.
> [...] Because the models are non-parametric here [...]

I am a bit puzzled here.

Sebastian
