### ISSUE TITLE
Kriging for geotif image

### ISSUE THREAD

**Issue by Empanag** [GeoStat-Framework/PyKrige#210]
Hello, i m trying to use kriging to tiff image. the image is that below with number 1 that can be used as an array, it is regular grid. the 2nd image is the one that saga simple kriging module generates. I 'd like to produce a similar product using python. Is it possible somehow PyKrige? I tried with the example "ordinary kriging" that there is in the site  had but the product was the same with input image.

![image](https://user-images.githubusercontent.com/61833032/128197703-ffed5b84-a287-4b4e-8ee8-1bc13e2964ee.png)

**Comment by Empanag** [comment]
i tried the code below but the product is the same with the input image 

```import numpy as np
import gstools as gs
import pykrige.kriging_tools as kt
from pykrige.ok import OrdinaryKriging
import matplotlib.pyplot as plt
from osgeo import gdal,ogr



filefolder="C:/Users/fermi/Desktop/SUEWS/SUEWSapp/kriging/"
rasterpath=filefolder+"T2UFfill_T2_01_14.tif"
print(rasterpath)
raster=gdal.Open(rasterpath)
print(raster)
rasterBand=raster.GetRasterBand(1)
rasterArray= rasterBand.ReadAsArray()
print(rasterArray.shape)

lstarray=[]
gridx = np.arange(3225.80, 3357.80, 1.0)
gridy = np.arange(39068.95, 39136.95, 1.0)
for i in range(len(gridx)):
    for j in range(len(gridy)):
        lstarray.append([gridx[i],gridy[j],rasterArray[j,i]])
rasterarray=np.array(lstarray)

cov_model = gs.Gaussian(dim=2, len_scale=0.1,  var=0.01)

OK2 = OrdinaryKriging(rasterarray[:, 0], rasterarray[:, 1], rasterarray[:, 2], variogram_model=cov_model)
z1, ss1 = OK2.execute("grid", gridx, gridy)

plt.imshow(np.flip(z1,0), origin="lower")
plt.show()

**Comment by MuellerSeb** [comment]
See: https://github.com/GeoStat-Framework/GSTools/discussions/199
