### ISSUE TITLE
Replicating Empirical Bayesian Kriging functionality

### ISSUE THREAD

**Issue by goriliukasbuxton** [GeoStat-Framework/PyKrige#214]
Has anyone done similar work like this tool? to get most optimal parameters for Kriging
https://pro.arcgis.com/en/pro-app/latest/help/analysis/geostatistical-analyst/what-is-empirical-bayesian-kriging-.htm

**Comment by MuellerSeb** [comment]
Isn't this the way sklearn fits the gaussian processes kernels?
https://scikit-learn.org/stable/modules/gaussian_process.html

**Comment by sachin9390** [comment]
my question is also same. I think its a special case of regression and kriging.
