### ISSUE TITLE
M1 Silicon Build (linux/arm64)

### ISSUE THREAD

**Issue by rmartell** [GeoStat-Framework/PyKrige#233]
Any thoughts on getting an M1 Build?  I'm having to run in a docker container with an emulated processor on an M1 Mac.  

I'm not familiar with Python toolchains, but would be more than happy to try and troubleshoot if you can give me some pointers for building.

**Comment by MuellerSeb** [comment]
We already implemented this for GSTools and I will apply the same procedure for the next PyKrige release.
