### ISSUE TITLE
search radius

### ISSUE THREAD

**Issue by AriesChen-UPC** [GeoStat-Framework/PyKrige#260]
### Ordinary Kriging
Is it possible to set the search radius？

**Comment by MuellerSeb** [comment]
Not yet. One can only specify the number of nearest neighbors to be used.

**Comment by MuellerSeb** [comment]
See here: https://github.com/GeoStat-Framework/PyKrige/issues/41

**Comment by AriesChen-UPC** [comment]
Okay, thank you for your reply!
