### ISSUE TITLE
Bug: pykrige.ok using deprecated function from SciPy 1.7.0

### ISSUE THREAD

**Issue by cesarofs** [GeoStat-Framework/PyKrige#261]
scipy.linalg.pinv2 is called by pykrige.ok for function OrdinaryKriging but this function is deprecated since SciPy 1.7.2, now SciPy is under version 1.9.2
When using SciPy version > 1.7.1, PyKrige does not works

**Comment by MuellerSeb** [comment]
This is already solved by #237

Please update to the latest version of pykrige
