### ISSUE TITLE
uk3d.execute prints statement of 'Executing Ordinary Kriging'

### ISSUE THREAD

**Issue by gmerritt123** [GeoStat-Framework/PyKrige#272]
Super minor but easy fix --> it made a colleague of mine nervous so I went an looked at the source code.

line 975 here -->https://github.com/GeoStat-Framework/PyKrige/blob/main/src/pykrige/uk3d.py
```
        if self.verbose:
            print("Executing Ordinary Kriging...\n")

```

Should be `print('Executing Universal Kriging...\n')`

**Comment by MuellerSeb** [comment]
Fixed by https://github.com/GeoStat-Framework/PyKrige/commit/eb86fb2ed5d373e25daf63ddc7657424bd7802b1
