### ISSUE TITLE
Cannot find reference 'OK' in 'pykrige.py | __init__.py' 

### ISSUE THREAD

**Issue by xddcode** [GeoStat-Framework/PyKrige#288]
![image](https://github.com/GeoStat-Framework/PyKrige/assets/48708512/caa09eb8-20a2-46e8-b5f7-6751d9ccae31)
I made sure pykrige package is installed
![image](https://github.com/GeoStat-Framework/PyKrige/assets/48708512/79b0a4a9-77d1-45a7-9811-b740a30a7d0b)

**Comment by MuellerSeb** [comment]
Hey there,

you need to use lowercase `ok` since python is case sensitive. See here for example: https://geostat-framework.readthedocs.io/projects/pykrige/en/v1.7.1/examples/00_ordinary.html

```python
from pykrige.ok import OrdinaryKriging
```
