### ISSUE TITLE
pykrige.test.TestRegressionKrige times out

### ISSUE THREAD

**Issue by rth** [GeoStat-Framework/PyKrige#62]
Travis CI occasionally fails because `pykrige.test.TestRegressionKrige` takes more than 10min to run (maximum allowed time). This seems to happen randomly, on other occasions in completes within seconds: see e.g.  https://github.com/bsmurphy/PyKrige/pull/61  where one Travis CI job passed, the other failed. 

I think the problem is that sometimes the test fails to download the test dataset with `fetch_california_housing` in https://github.com/bsmurphy/PyKrige/blob/master/pykrige/test.py#L1726 . In any case it might be a good idea to replace this with a built-in dataset that doesn't require to be downloaded.

cc @basaks

**Comment by basaks** [comment]
@rth I need a bit more time to check this out.
You are right in saying that may be we can keep a small copy of the data in this repo for these tests.

**Comment by MuellerSeb** [comment]
Is working fine with #131 . Feel free to re-open if I am wrong.
