### ISSUE TITLE
Make matplotlib an optional dependency

### ISSUE THREAD

**Issue by rth** [GeoStat-Framework/PyKrige#63]
Currently matplotlib is a hard dependency and it is imported as `import matplotlib.pyplot as plt` at the top of most source files. It might be better to make it an optional dependency so that krigging would still work even if matplotlib is not installed and the plotting would fail with some explicit error message asking to install matplotlib. 

This is in particularly useful when computing kriging on a remote server, where plotting might not be best suited anyway.

**Comment by bsmurphy** [comment]
Agreed, do you think placing it as an import directly in the functions where it's used would be best? (I believe those would just be the user interface functions/methods, like plot_variogram and stuff like that...)

**Comment by MuellerSeb** [comment]
Done with `v1.5`
