### ISSUE TITLE
Maximal distance in variogram estimation

### ISSUE THREAD

**Issue by gregblt** [GeoStat-Framework/PyKrige#97]
Hi!

I want to perform ordinary kringing and I have a question : Can we choose the maximal distance for the variogram estimation?

Thank you for this nice python module!

**Comment by bsmurphy** [comment]
Currently there isn't an explicit way to do this in the package (see #57, related). Adding support for this is on the long-term list of features to add. But in the mean time, you can hack the auto variogram estimation routine to enforce some cutoff. You can find that code in the ```core``` module.

Thanks for your interest!

**Comment by MuellerSeb** [comment]
Closing in favor of #57

**Comment by MuellerSeb** [comment]
See #136
